### PR TITLE
Babel 7 support

### PR DESCRIPTION
**Pull request by igorkamyshev**
Hello! Great lib, thanks a lot!

I try to solve #7 .

Please review my PR and give me your feedback.

### CODE REVIEW

**Comment by igorkamyshev** [comment]
@developit , hey.

**Comment by igorkamyshev** [comment]
@developit, hello! =)

**Comment by dmorenogogoleva** [comment]
🔥

**Review by enricopolanski — APPROVED** [review]

**Comment by Uncleseneca** [comment]
@VulcanRav Thanks for a great library!
I'd be happy to use it with babel 7!

**Comment by enricopolanski** [comment]
@Uncleseneca the library is not mine.

I simply tested the pr in my environment and found it working, with all my e2e tests passing.

**Comment by Carnewal** [comment]
:+1:

**Comment by tomasdev** [comment]
This does not fix it for Babel 7, it will still complain about plugins cannot export objects.

It has to be a function. See my PR.

**Pull request closed without merging**
