### PR TITLE
Support Babel 7

### LINKED ISSUE #7: Babel 7 support
Hello!

Great lib, I use it in my pet-project. Thanks.

Babel 7 was released. Maybe add support it this plugin?

### PR DESCRIPTION
**Pull request by tomasdev**
Based on https://github.com/babel/babel/pull/6494

Tried in my local and worked great, not sure if it's backwards compatible with Babel 6.

Fixes #7

### CODE REVIEW

**Review by dancrew32 — APPROVED** [review]
lgtm! tried the edit in `vim ./node_modules/babel-preset-preact/index.js` and parcel runs fine now.

**Comment by janbaer** [comment]
@developit Could you please approve and merge it. We would like to migrate to Babel7. Thanks!

**Comment by matthewhartman** [comment]
Can we please merge this :100:

**Review by matthewhartman — APPROVED** [review]
Looks good! :+1:

**Review by jonaswide — APPROVED** [review]

**Comment by vqrulane** [comment]
It seems to work.

**Review by vqrulane — APPROVED** [review]
Works correctly with Babel 7 and Webpack.

**Comment by seanstrom** [comment]
Hey @tomasdev 👋

Seems that **Babel 7** support is now accomplished by using the [@babel/plugin-transform-react-jsx](https://babeljs.io/docs/en/next/babel-plugin-transform-react-jsx.html) plugin as recommended in the [Getting Started Documentation](https://preactjs.com/guide/getting-started).

An example `.babelrc`
```json
{
  "plugins": [
    ["@babel/plugin-transform-react-jsx", { "pragma":"h" }]
  ]
}
```

Does this resolve the need for this PR?

**Comment by tomasdev** [comment]
I believe I was getting an error because plugins in Babel 7 must export functions, not objects. Maybe.

**Comment by seanstrom** [comment]
It seems that several presets in the ecosystem became incompatible as well, such as `babel-preset-react`, and the alternative became a new package named `@babel/preset-react` for Babel 7 support. Unfortunately this package has not received the same upgrades yet, so I wanted to leave a note that may help out in the short term. I think the above `.babelrc` snippet accomplishes what this preset is doing for a Babel 6 project.

**Review by developit — APPROVED** [review]

**Pull request merged**
